spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kalahDB;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true